name: LaTeX build

on: [push]  # This triggers the workflow when you push changes to the repository

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu

    steps:
    - uses: actions/checkout@v2  # Checkout your repository code

    - name: Install LaTeX
      run: sudo apt-get install -y texlive-full  # Install LaTeX

    - name: Compile LaTeX document
      run: pdflatex codebook testing.tex  # Replace 'main.tex' with your .tex file name

    - name: Upload PDF
      uses: actions/upload-artifact@v2
      with:
        name: codebook  # Name of the PDF artifact
        path: main.pdf  # The generated PDF file
